services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend_app
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./backend:/var/www/html
    environment:
      - XDEBUG_MODE=debug,develop
    depends_on:
      - database
    networks:
      - forecast-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend_app
    develop:
      watch:
        - action: sync
          path: ./src
          target: /app/src
          ignore:
            - node_modules
        - action: rebuild
          path: package.json
    ports:
      - 8080:8080
      - 9229:9229
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - forecast-network

  database:
    image: mysql:8.2
    container_name: mysql_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: laravel_db
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: laravel_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - forecast-network

volumes:
  db_data:

networks:
  forecast-network: